os: Visual Studio 2019

clone_depth: 1

branches:
  only:
    - main
    - develop
    - next
    - /try.*/
    - /dev.*/
    - /release-.*/

environment:
  github_access_token:
    secure: "ogfTv7V0xR13ETjrC+koS7ZURfl0KLRfwcjYBexoiB1gcc5pppO/H42BopJWl0ua"

install:
  # Install Chocolatey if not already installed
  - powershell -NoProfile -InputFormat None -ExecutionPolicy Bypass -Command "iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))"
  # Install hyperfine without reboot
  - choco install hyperfine --params "/norestart"
  # NSIS Paths
  # https://www.appveyor.com/docs/build-environment/#tools
  - set PATH=%PATH%;C:\Program Files (x86)\NSIS
  # Python stdout encoding 
  - set PYTHONIOENCODING=utf-8


build_script:
  # 32-bit version
  - ps: Write-Host "Building the 32-bit variant."
  - py -3.10-32  -m venv .venv32
  - call ".venv32\Scripts\activate.bat"
  - python -m pip install invoke
  - invoke dev
  - python -m pytest -vvv
  - invoke build
  - invoke create-portable
  - invoke bench
  - deactivate
  # 64-bit version
  - ps: Write-Host "Building the 64-bit variant."
  - py -3.10-64 -m venv .venv64
  - call ".venv64\Scripts\activate.bat"
  - python -m pip install invoke
  - invoke dev
  - python -m pytest -vvv
  - invoke build
  - invoke create-portable
  - invoke bench
  # Update the release info file
  - invoke update-version-info
  - invoke gen-pot


artifacts:
  - path: scripts\Bookworm*setup.exe
  - path: scripts\Bookworm*update.bundle
  - path: scripts\Bookworm*portable.zip
  - path: scripts\release-info.json
  - path: scripts\benchmark*.json
  - path: scripts\bookworm*.pot


on_success:
  - ps: |
      if ($env:APPVEYOR_REPO_TAG_NAME -and $env:APPVEYOR_REPO_TAG_NAME.StartsWith("release-")) {
        echo "Updating version information for this release." 
      }


deploy:
  release: "Bookworm Release (Build v$(appveyor_build_version))"
  description: "Uploaded from appveyor by the build bot"
  provider: GitHub
  auth_token:
    secure: "ogfTv7V0xR13ETjrC+koS7ZURfl0KLRfwcjYBexoiB1gcc5pppO/H42BopJWl0ua"
  artifact: /Bookworm-.*-setup\.exe/, /Bookworm-.*-update\.bundle/, /Bookworm-.*-portable\.zip/, /release-info\.json/, /bookworm-.*\.pot/, /benchmark.*\.json/
  draft: true
  prerelease: true
  on:
    APPVEYOR_REPO_TAG: true
